version: 0.2
phases:
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --template-file template.yml --output-template-file packaged-template.yml --s3-bucket test-bucket-for-mhirayam
artifacts:
  files:
    - packaged-template.yml
